#!/usr/bin/env bash

set -euo pipefail

fail() {
  printf 'security-scope-test: %s\n' "$*" >&2
  exit 1
}

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
view_script="${repo_root}/scripts/pcplab-external-lock-view.sh"
workflow="${repo_root}/.github/workflows/pcplab-security.yml"
[[ -x "$view_script" ]] || fail 'external lockfile view script is missing or not executable'

tmp_root=${TMPDIR:-/tmp}
tmp_dir=$(mktemp -d "${tmp_root}/pcplab-security-scope.XXXXXX")
cleanup() {
  case "$tmp_dir" in
    "${tmp_root}"/pcplab-security-scope.*) rm -rf -- "$tmp_dir" ;;
    *) fail "refusing to remove unexpected path: $tmp_dir" ;;
  esac
}
trap cleanup EXIT

base_lock="${tmp_dir}/base.lock"
candidate_lock="${tmp_dir}/candidate.lock"
base_view="${tmp_dir}/base.view"
candidate_view="${tmp_dir}/candidate.view"

write_base() {
  cat >"$base_lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "company-local"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
dependencies = [
 "serde_core",
]

[[package]]
name = "serde_core"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2222222222222222222222222222222222222222222222222222222222222222"

[[patch.unused]]
name = "future-proofing"
version = "1.0.0"
source = "git+https://example.invalid/repository"
LOCK
}

compare_views() {
  "$view_script" "$base_lock" >"$base_view"
  "$view_script" "$candidate_lock" >"$candidate_view"
  cmp -s "$base_view" "$candidate_view"
}

expect_same() {
  compare_views || fail "$1 should not change the external dependency graph"
}

expect_different() {
  if compare_views; then
    fail "$1 must change the external dependency graph"
  fi
}

write_base
cp "$base_lock" "$candidate_lock"
sed -i 's/company-local/company-local-renamed/' "$candidate_lock"
expect_same 'local package changes'

write_base
cp "$base_lock" "$candidate_lock"
sed -i '/ "serde",/a\ "company-local-new",' "$candidate_lock"
sed -i '/^\[\[patch\.unused\]\]$/i\
[[package]]\
name = "company-local-new"\
version = "0.1.0"\
dependencies = [\
 "serde",\
]\
' "$candidate_lock"
expect_same 'local package additions and local dependency-list changes'

write_base
cp "$base_lock" "$candidate_lock"
sed -i 's/version = "1.0.0"/version = "1.0.1"/' "$candidate_lock"
expect_different 'external version changes'

write_base
cp "$base_lock" "$candidate_lock"
sed -i 's/checksum = "1111111111111111111111111111111111111111111111111111111111111111"/checksum = "9999999999999999999999999999999999999999999999999999999999999999"/' "$candidate_lock"
expect_different 'external checksum changes'

write_base
cp "$base_lock" "$candidate_lock"
sed -i 's#registry+https://github.com/rust-lang/crates.io-index#git+https://example.invalid/serde#' "$candidate_lock"
expect_different 'external source changes'

write_base
cp "$base_lock" "$candidate_lock"
sed -i '/ "serde_core",/a\ "new-feature-dependency",' "$candidate_lock"
expect_different 'external dependency-array changes'

write_base
cp "$base_lock" "$candidate_lock"
sed -i 's/version = 4/version = 5/' "$candidate_lock"
expect_different 'lockfile format changes'

write_base
cp "$base_lock" "$candidate_lock"
cat >>"$candidate_lock" <<'LOCK'

[[package]]
name = "new-external"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3333333333333333333333333333333333333333333333333333333333333333"
LOCK
expect_different 'external package additions'

write_base
awk 'BEGIN { dropping=0 } /^\[\[package\]\]$/ { if (dropping) dropping=0; block=$0; next } block != "" { block=block "\n" $0; if ($0 == "name = \"serde_core\"") dropping=1; if ($0 == "") { if (!dropping) print block; block="" } next } { print } END { if (block != "" && !dropping) print block }' "$base_lock" >"$candidate_lock"
expect_different 'external package removals'

grep -Fq 'bash scripts/pcplab-external-lock-view.sh' "$workflow" \
  || fail 'security workflow does not use the tested external lockfile view'
grep -Fq '^scripts/pcplab-external-lock-view\.sh$' "$workflow" \
  || fail 'changing the external lockfile view must force the full Rust security scan'
grep -Fq '[ "$EVENT_NAME" = merge_group ]' "$workflow" \
  || fail 'merge queue must force the full Rust security scan'
grep -Fq '[[ "$HEAD_REF" == sync/upstream-* ]]' "$workflow" \
  || fail 'upstream sync branches must force the full Rust security scan'
grep -Fq '[[ "$HEAD_REF" == sync/security-* ]]' "$workflow" \
  || fail 'security sync branches must force the full Rust security scan'
grep -Fq '^deny\.toml$|^rust-toolchain\.toml$|^\.github/workflows/pcplab-security\.yml$' "$workflow" \
  || fail 'security policy and toolchain changes must force the full Rust security scan'
grep -Fq '! git cat-file -e "${HEAD_SHA}^{commit}"' "$workflow" \
  || fail 'an unresolvable head SHA must force the full Rust security scan'
grep -Fq 'if ! grep -Eq '\''(^|/)Cargo\.lock$'\'' <<<"$changed"' "$workflow" \
  || fail 'manifest-only dependency changes must force the full Rust security scan'
grep -Fq "Root tooling does not audit independent nested lockfiles" "$workflow" \
  || fail 'nested Cargo.lock changes must force the full Rust security scan'
grep -Fq "Missing/unparseable lockfiles fail closed" "$workflow" \
  || fail 'lockfile comparison failures must force the full Rust security scan'

local_only_lock="${tmp_dir}/local-only.lock"
cat >"$local_only_lock" <<'LOCK'
version = 4

[[package]]
name = "company-local"
version = "0.1.0"
LOCK
if "$view_script" "$local_only_lock" >/dev/null 2>&1; then
  fail 'a nonempty lockfile with no external package records must fail closed'
fi

printf 'security-scope-test: PASS\n'
